package com.igobrilhante.github.akka.interfaces.adapters

import com.igobrilhante.github.adapters.json.circle.CircleJsonEntitiesAdapters
import de.heikoseeberger.akkahttpcirce.FailFastCirceSupport

trait AkkaHttpCircleJsonEntitiesAdapters extends CircleJsonEntitiesAdapters with FailFastCirceSupport

object AkkaHttpCircleJsonEntitiesAdapters extends AkkaHttpCircleJsonEntitiesAdapters
